version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=bureau
      - POSTGRES_PASSWORD=bureau
      -  PGDATABASE=db_bureau
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data